### ISSUE TITLE
Building under ncs

### ISSUE THREAD

**Issue by kapollo** [Riphiphip/zephyr-uart-driver-example#1]
How to build the example under ncs, when using west init I get a message that it is already initialized (using bash from toolchain manager)

**Comment by Riphiphip** [comment]
To build using an ncs toolchain from the toolchain manager you could try cloning this repo, opening a shell from the toolchain manager, navigate to the cloned repo and running ```west build``` with whatever board you're using. I got that to work on my machine, but it's quite polluted with different ncs/zephyr installations which may have affected my results.

If this works for you I will add a section on it to README.
